/*
    * This source file was generated by the Gradle 'init' task
    * Para rodar o código no terminal do VSCode, é necessário executar os seguintes comandos:
        * 1- kotlinc App.kt -include-runtime -d App.jar
        * 2- java -jar App.jar
    *O uso de outros comandos para compilar e executar o código pode não funcionar corretamente.
 */
package org.example

class App {
    fun calculaSalario(): Double{
        print("Digite o salario: ")
        val salario = readLine()?.toDoubleOrNull()
        if (salario == null || salario <= 0) {
            throw IllegalArgumentException("Salario invalido. Por favor, insira um número positivo.")
        }

        print("Digite o beneficio: ")
        val beneficio = readLine()?.toDoubleOrNull()
        if (beneficio == null || beneficio < 0) {
            throw IllegalArgumentException("Benefício invalido. Por favor, insira um número não negativo.")
        }

        var aliquota: Double = when {
            salario > 0 && salario <= 1100 -> 0.05
            salario > 1100 && salario <= 2500 -> 0.1
            else -> 0.15
        }

        val imposto = salario * aliquota;
        val salarioLiquido = (salario - imposto) + beneficio;
        return salarioLiquido
    }
}

fun main() {
    val app = App()
    try {
        println("Salário líquido: ${String.format("%.2f", app.calculaSalario())}")
    } catch (e: IllegalArgumentException) {
        println("Erro: ${e.message}")
    }    
}
