/*
    * This source file was generated by the Gradle 'init' task
    * Para rodar o código no terminal do VSCode, é necessário executar os seguintes comandos:
        * 1- kotlinc App.kt -include-runtime -d App.jar
        * 2- java -jar App.jar
    *O uso de outros comandos para compilar e executar o código pode não funcionar corretamente.
 */
package org.example

object ReceitaFederal{
    fun calculaImposto(salario: Double): Double{
        val aliquota = when {
            salario > 0 && salario <= 1100 -> 0.05
            salario > 1100 && salario <= 2500 -> 0.1
            else -> 0.15
        }
        return salario * aliquota
    }
}

fun main() {
    println("Digite o salário: ")
    val salario = readLine()!!.toDouble()

    println("Digite o benefício: ")
    val beneficio = readLine()!!.toDouble()

    val imposto = ReceitaFederal.calculaImposto(salario)
    val salarioLiquido = (salario - imposto) + beneficio
    
    println(String.format("Salário: %.2f", salarioLiquido))
}
